name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Use Node.js 16 as it's supported by the legacy expo-cli

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npx expo export --public-url https://michaeljohnpena.com

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # This is the default output directory for Expo export
        cname: michaeljohnpena.com  # This will create a CNAME file in the gh-pages branch